// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6vnovDN3P95EmZI2nhIcVzkBS0FFKff0',
    appId: '1:2162451845:web:b9e5c5cadab8556f3fd0ec',
    messagingSenderId: '2162451845',
    projectId: 'taska-3b887',
    authDomain: 'taska-3b887.firebaseapp.com',
    storageBucket: 'taska-3b887.firebasestorage.app',
    measurementId: 'G-YN4L4LBGMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDHfRsPG3JkoZ32D_aQ8ISZB4Y5Q9TN9E',
    appId: '1:2162451845:android:920a5493beea910b3fd0ec',
    messagingSenderId: '2162451845',
    projectId: 'taska-3b887',
    storageBucket: 'taska-3b887.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5dIV0FimA7vc3wZ44Fk9aP7KYO_0NlO8',
    appId: '1:2162451845:ios:330e8aa1989900293fd0ec',
    messagingSenderId: '2162451845',
    projectId: 'taska-3b887',
    storageBucket: 'taska-3b887.firebasestorage.app',
    iosBundleId: 'com.example.taska',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5dIV0FimA7vc3wZ44Fk9aP7KYO_0NlO8',
    appId: '1:2162451845:ios:330e8aa1989900293fd0ec',
    messagingSenderId: '2162451845',
    projectId: 'taska-3b887',
    storageBucket: 'taska-3b887.firebasestorage.app',
    iosBundleId: 'com.example.taska',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6vnovDN3P95EmZI2nhIcVzkBS0FFKff0',
    appId: '1:2162451845:web:5a22b492c70940103fd0ec',
    messagingSenderId: '2162451845',
    projectId: 'taska-3b887',
    authDomain: 'taska-3b887.firebaseapp.com',
    storageBucket: 'taska-3b887.firebasestorage.app',
    measurementId: 'G-NTHR7ZD21D',
  );
}
